include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GoodWiFi

GoodWiFi_FILES = GoodWiFi.xm
GoodWiFi_FRAMEWORKS = CydiaSubstrate UIKit Security
GoodWiFi_PRIVATE_FRAMEWORKS = MobileWiFi

include $(THEOS_MAKE_PATH)/tweak.mk
