include theos/makefiles/common.mk

BUNDLE_NAME = GoodWiFiSettings
GoodWiFiSettings_FILES = /mnt/d/codes/goodwifi/goodwifisettings/GoodWiFiSettingsController.mm
GoodWiFiSettings_INSTALL_PATH = /Library/PreferenceBundles
GoodWiFiSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
GoodWiFiSettings_PRIVATE_FRAMEWORKS = Preferences
GoodWiFiSettings_CFLAGS = -fobjc-arc
GoodWiFiSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk

all::
