include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = GoodWiFiSettings
GoodWiFiSettings_FILES = GoodWiFiSettingsController.mm
GoodWiFiSettings_INSTALL_PATH = /Library/PreferenceBundles
GoodWiFiSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
GoodWiFiSettings_PRIVATE_FRAMEWORKS = Preferences
GoodWiFiSettings_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
